### ISSUE TITLE
default() vs new() for struct update syntax

### ISSUE THREAD

**Issue by Yamakaky** [brson/rust-api-guidelines#54]
[C-CTOR](https://github.com/brson/rust-api-guidelines#constructors-are-static-inherent-methods-c-ctor) suggest to use `Struct::new()`. I saw also the use of `Default::default()`, like in https://tomaka.github.io/glium/glium/draw_parameters/struct.DrawParameters.html. Maybe a point could be added about when to use which.

**Comment by newpavlov** [comment]
I somewhere seen a recommendation to prefer `Default` over empty `new()` method. Following it I removed `new()` for crypto-hashes crates and only left for cases when some additional arguments must be passed for hash initialization.

But now I am considering to add `new()` to `Digest` trait implemented as `fn new() -> Self { Self::default() }`. For example it simply does not look right to call `Sha256::default()` instead of `Sha256::new()`. Yes, it will be somewhat redundant, but stylistically more appealing.

But anyway it will be indeed nice to have some rules regarding `default()` vs `new()`.

**Comment by dtolnay** [comment]
We will follow up on this as part of #38.
